<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mowerbot_hmi</name>
  <version>0.0.0</version>
  <description>mowerbot 的人機介面 (HMI)：模式切換與系統狀態顯示</description>
  <maintainer email="a0987747836@gmail.com">a</maintainer>
  <license>TODO: License declaration</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>mowerbot_interfaces</exec_depend>
  <exec_depend>mowerbot_action</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <!-- Ubuntu 上是 python3-pyqt5 套件 -->
  <exec_depend>python3-pyqt5</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
